import React from "react";
const columns = [
  {name: "ID", uid: "id", sortable: true},
  {name: "FIRSTNAME", uid: "firstname", sortable: true},
  {name: "LASTNAME", uid: "lastname", sortable: true},
  {name: "COUNTRY", uid: "country", sortable: true},
  {name: "CITYOFFICE", uid: "cityoffice",sortable:true},
  {name: "ROLE", uid: "role", sortable: true},
  {name: "EMAIL", uid: "email"},
  {name: "SENIORITY", uid: "seniority"},
  {name: "BIRTHDAY", uid: "birthday"},
  {name: "STATE OF EMPLOYEMENT", uid: "soe"},
  {name: "STARTDATE", uid: "startdate",sortable:true},
  {name: "ENDDATE", uid: "enddate",sortable:true},
  {name: "STATUS", uid: "status", sortable: true},
  {name:"NATIONALITY",uid:"nationality",sortable:true},
  {name: "ACTIONS", uid: "actions"},
];

const statusOptions = [
  {name: "Active", uid: "active"},
  {name: "NotActive", uid: "notactive"},
];

const users = [
  {
    id: 1,
    firstname: "Tony",
    lastname: " Reichert",
    country:"Germany",
    cityoffice:"office1",
    role: "CEO",
    email: "tony.reichert@example.com",
    seniority:"Senior",
    birthday:"",
    soe:"Employed",
    startdate:"12-04-2017",
    enddate:"",
    status: "active",
    nationality:"germany",
  },
  {
    id: 2,
    firstname: "James",
    lastname: "Williams",
    country:"Germany",
    cityoffice:"office1",
    role: "CFO",
    email: "james.williams@example.com",
    seniority:"Senior",
    birthday:"",
    soe:"Employed",
    startdate:"16-04-2017",
    enddate:"",
    status: "active",
    nationality:"india",
  },
  {
    id: 3,
    firstname: "Ricky",
    lastname: "Auther",
    country:"Germany",
    cityoffice:"office2",
    role: "CTO",
    email: "ricky.auther@example.com",
    seniority:"Senior",
    birthday:"",
    soe:"Employed",
    startdate:"18-04-2017",
    enddate:"",
    status: "active",
    nationality:"america",
  },
  {
    id: 4,
    firstname: "Martin",
    lastname: "Luther",
    country:"Germany",
    cityoffice:"office2",
    role: "CO",
    email: "martin.luther@example.com",
    seniority:"Senior",
    birthday:"",
    soe:"Employed",
    startdate:"20-04-2017",
    enddate:"",
    status: "active",
    nationality:"france",
    
  },
  {
    id: 5,
    firstname: "Blaize",
    lastname: "kalli",
    country:"Germany",
    cityoffice:"office2",
    role: "Employee",
    email: "blaize.kalli@example.com",
    seniority:"Junior",
    birthday:"",
    soe:"Employed",
    startdate:"20-04-2017",
    enddate:"",
    status: "active",
    nationality:"africa",
  },
  {
    id: 6,
    firstname: "iianfa",
    lastname: " Rert",
    country:"Turkey",
    cityoffice:"office1",
    role: "Employee",
    email: "iianfa.Rert@example.com",
    seniority:"Junior",
    birthday:"19-01-2000",
    soe:"Employed",
    startdate:"12-04-2017",
    enddate:"20-10-2022",
    status: "notactive",
    nationality:"turkey",
  },
  {
    id: 7,
    firstname: "Tony",
    lastname: " Reichert",
    country:"Germany",
    cityoffice:"office1",
    role: "CEO",
    email: "tony.reichert@example.com",
    seniority:"Senior",
    birthday:"",
    soe:"Employed",
    startdate:"12-04-2017",
    enddate:"",
    status: "active",
    nationality:"germany",
  },
  {
    id: 8,
    firstname: "Tony",
    lastname: " Reichert",
    country:"Germany",
    cityoffice:"office1",
    role: "CEO",
    email: "tony.reichert@example.com",
    seniority:"Senior",
    birthday:"",
    soe:"Employed",
    startdate:"12-04-2017",
    enddate:"",
    status: "active",
    nationality:"germany",
  },
  {
    id: 9,
    firstname: "Tony",
    lastname: " Reichert",
    country:"Germany",
    cityoffice:"office1",
    role: "CEO",
    email: "tony.reichert@example.com",
    seniority:"Senior",
    birthday:"",
    soe:"Employed",
    startdate:"12-04-2017",
    enddate:"           ",
    status: "active",
    nationality:"germany",
  },
  {
    id: 10,
    firstname: "Tony",
    lastname: " Reichert",
    country:"Germany",
    cityoffice:"office1",
    role: "CEO",
    email: "tony.reichert@example.com",
    seniority:"Senior",
    birthday:"",
    soe:"Employed",
    startdate:"12-04-2017",
    enddate:"",
    status: "active",
    nationality:"germany",
  },
  {
    id: 11,
    firstname: "Tony",
    lastname: " Reichert",
    country:"Germany",
    cityoffice:"office1",
    role: "CEO",
    email: "tony.reichert@example.com",
    seniority:"Senior",
    birthday:"",
    soe:"Employed",
    startdate:"12-04-2017",
    enddate:"",
    status: "active",
    nationality:"germany",
  },
  {
    id: 12,
    firstname: "Tony",
    lastname: " Reichert",
    country:"Germany",
    cityoffice:"office1",
    role: "CEO",
    email: "tony.reichert@example.com",
    seniority:"Senior",
    birthday:"",
    soe:"Employed",
    startdate:"12-04-2017",
    enddate:"",
    status: "active",
    nationality:"germany",
  },
  {
    id: 13,
    firstname: "Tony",
    lastname: " Reichert",
    country:"Germany",
    cityoffice:"office1",
    role: "CEO",
    email: "tony.reichert@example.com",
    seniority:"Senior",
    birthday:"",
    soe:"Employed",
    startdate:"12-04-2017",
    enddate:"",
    status: "active",
    nationality:"germany",
  },
  {
    id: 14,
    firstname: "Tony",
    lastname: " Reichert",
    country:"Germany",
    cityoffice:"office1",
    role: "CEO",
    email: "tony.reichert@example.com",
    seniority:"Senior",
    birthday:"",
    soe:"Employed",
    startdate:"12-04-2017",
    enddate:"",
    status: "active",
    nationality:"germany",
  },
  {
    id: 15,
    firstname: "Tony",
    lastname: " Reichert",
    country:"Germany",
    cityoffice:"office1",
    role: "CEO",
    email: "tony.reichert@example.com",
    seniority:"Senior",
    birthday:"",
    soe:"Employed",
    startdate:"12-04-2017",
    enddate:"",
    status: "active",
    nationality:"germany",
  },
  {
    id: 16,
    firstname: "Waffer",
    lastname: " Reichert",
    country:"Germany",
    cityoffice:"office1",
    role: "CEO",
    email: "waffer.reichert@example.com",
    seniority:"Senior",
    birthday:"",
    soe:"Employed",
    startdate:"12-04-2017",
    enddate:"",
    status: "active",
    nationality:"germany",
  },
  {
    id: 17,
    firstname: "avinash",
    lastname: "siripuram",
    country:"India",
    cityoffice:"office2",
    role: "Developer",
    email: "avinash.siripuram@example.com",
    seniority:"Junior",
    birthday:"05-04-2002",
    soe:"Employed",
    startdate:"12-04-2017",
    enddate:"",
    status: "active",
    nationality:"germany",
  },
  {
    id: 18,
    firstname: "Lucy",
    lastname: " Reichert",
    country:"Turkey",
    cityoffice:"office1",
    role: "Intern",
    email: "lucy.reichert@example.com",
    seniority:"Junior",
    birthday:"12-05-1999",
    soe:"Employed",
    startdate:"12-04-2017",
    enddate:"",
    status: "active",
    nationality:"germany",
  },
  {
    id: 19,
    firstname: "Tony",
    lastname: " Addam",
    country:"Germany",
    cityoffice:"office1",
    role: "Intern",
    email: "tony.addam@example.com",
    seniority:"Junior",
    birthday:"",
    soe:"FormerlyEmployed",
    startdate:"12-04-2017",
    enddate:"20-09-2023",
    status: "notactive",
    nationality:"germany",
  },

];

export {columns, users, statusOptions};
