export const employees = [
    {
      empId: 1,
      name: "Tony Reichert",
      phoneno:"949474944",
      email: "tony.reichert@example.com",
      mana1Id:"5",
      mana2Id:"5",
      actions:"",
    },
    {
      empId: 2,
      name: "Tony Reichert",
      phoneno:"949474944",
      email: "tony.reichert@example.com",
      mana1Id:"5",
      mana2Id:"5",
      actions:"",
    },
    {
      empId: 3,
      name: "Tony Reichert",
      phoneno:"949474944",
      email: "tony.reichert@example.com",
      mana1Id:"5",
      mana2Id:"5",
      actions:"",
    },
    {
      empId: 4,
      name: "Tony Reichert",
      phoneno:"949474944",
      email: "tony.reichert@example.com",
      mana1Id:"5",
      mana2Id:"5",
      actions:"",
    },
    {
      empId: 5,
      name: "Tony Reichert",
      phoneno:"949474944",
      email: "tony.reichert@example.com",
      mana1Id:"5",
      mana2Id:"5",
      actions:"",
    },
    {
      empId: 6,
      name: "Tony Reichert",
      phoneno:"949474944",
      email: "tony.reichert@example.com",
      mana1Id:"5",
      mana2Id:"5",
      actions:"",
    },
    {
      empId: 7,
      name: "Tony Reichert",
      phoneno:"949474944",
      email: "tony.reichert@example.com",
      mana1Id:"5",
      mana2Id:"5",
      actions:"",
    },
    {
      empId: 8,
      name: "Tony Reichert",
      phoneno:"949474944",
      email: "tony.reichert@example.com",
      mana1Id:"5",
      mana2Id:"5",
      actions:"",
    },
    {
      empId: 9,
      name: "Tony Reichert",
      phoneno:"949474944",
      email: "tony.reichert@example.com",
      mana1Id:"5",
      mana2Id:"5",
      actions:"",
    },
    {
      empId: 10,
      name: "Tony Reichert",
      phoneno:"949474944",
      email: "tony.reichert@example.com",
      mana1Id:"5",
      mana2Id:"5",
      actions:"",
    },
    {
      empId: 11,
      name: "Tony Reichert",
      phoneno:"949474944",
      email: "tony.reichert@example.com",
      mana1Id:"5",
      mana2Id:"5",
      actions:"",
    },
    {
      empId: 12,
      name: "Tony Reichert",
      phoneno:"949474944",
      email: "tony.reichert@example.com",
      mana1Id:"5",
      mana2Id:"5",
      actions:"",
    },
    {
      empId: 13,
      name: "Tony Reichert",
      phoneno:"949474944",
      email: "tony.reichert@example.com",
      mana1Id:"5",
      mana2Id:"5",
      actions:"",
    },
    {
      empId: 14,
      name: "Tony Reichert",
      phoneno:"949474944",
      email: "tony.reichert@example.com",
      mana1Id:"5",
      mana2Id:"5",
      actions:"",
    },
    {
      empId: 15,
      name: "Tony Reichert",
      phoneno:"949474944",
      email: "tony.reichert@example.com",
      mana1Id:"5",
      mana2Id:"5",
      actions:"",
    },
    {
      empId: 16,
      name: "Tony Reichert",
      phoneno:"949474944",
      email: "tony.reichert@example.com",
      mana1Id:"5",
      mana2Id:"5",
      actions:"",
    },
    {
      empId: 17,
      name: "Tony Reichert",
      phoneno:"949474944",
      email: "tony.reichert@example.com",
      mana1Id:"5",
      mana2Id:"5",
      actions:"",
    },
    {
      empId: 18,
      name: "Tony Reichert",
      phoneno:"949474944",
      email: "tony.reichert@example.com",
      mana1Id:"5",
      mana2Id:"5",
      actions:"",
    },
    {
      empId: 19,
      name: "Tony Reichert",
      phoneno:"949474944",
      email: "tony.reichert@example.com",
      mana1Id:"5",
      mana2Id:"5",
      actions:"",
    },
    {
      empId: 20,
      name: "Tony Reichert",
      phoneno:"949474944",
      email: "tony.reichert@example.com",
      mana1Id:"5",
      mana2Id:"5",
      actions:"",
    },
  ];