import React from "react";
export const Assets = [
  {
    asstID: "1",
    asstName: "Laptop",
    empId: "12",
    empName:"Uday",
    actions:"",
  },
  {
    asstID: "2",
    asstName: "Laptop",
    empId: "12",
    empName:"Uday",
    actions:"",
  },
  {
    asstID: "3",
    asstName: "Laptop",
    empId: "12",
    empName:"Uday",
    actions:"",
  },
  {
    asstID: "4",
    asstName: "Laptop",
    empId: "12",
    empName:"Uday",
    actions:"",
  },
  {
    asstID: "5",
    asstName: "Laptop",
    empId: "12",
    empName:"Uday",
    actions:"",
  },
  {
    asstID: "6",
    asstName: "Laptop",
    empId: "12",
    empName:"Uday",
    actions:"",
  },
  {
    asstID: "7",
    asstName: "Laptop",
    empId: "12",
    empName:"Uday",
    actions:"",
  },
  {
    asstID: "8",
    asstName: "Laptop",
    empId: "12",
    empName:"Uday",
    actions:"",
  },
  {
    asstID: "9",
    asstName: "Laptop",
    empId: "12",
    empName:"Uday",
    actions:"",
  },
  {
    asstID: "10",
    asstName: "Laptop",
    empId: "12",
    empName:"Uday",
    actions:"",
  },
  {
    asstID: "11",
    asstName: "Laptop",
    empId: "12",
    empName:"Uday",
    actions:"",
  },
  {
    asstID: "12",
    asstName: "Laptop",
    empId: "12",
    empName:"Uday",
    actions:"",
  },
  {
    asstID: "13",
    asstName: "Laptop",
    empId: "12",
    empName:"Uday",
    actions:"",
  },
  {
    asstID: "14",
    asstName: "Laptop",
    empId: "12",
    empName:"Uday",
    actions:"",
  },
  {
    asstID: "15",
    asstName: "Laptop",
    empId: "12",
    empName:"Uday",
    actions:"",
  },
  {
    asstID: "16",
    asstName: "Laptop",
    empId: "12",
    empName:"Uday",
    actions:"",
  },
  {
    asstID: "17",
    asstName: "Laptop",
    empId: "12",
    empName:"Uday",
    actions:"",
  },
  
  {
    asstID: "19",
    asstName: "Laptop",
    empId: "12",
    empName:"Uday",
    actions:"",
  },
  {
    asstID: "20",
    asstName: "Laptop",
    empId: "12",
    empName:"Uday",
    actions:"",
  },
];
